Repository LL-MnM/MnM, pull requests merged in 2023-07, with the labels that each got.

#41 메인페이지 로고 추가 & 소개 페이지 구현
  src/main/java/com/example/MnM/boundedContext/HomeController.java
  src/main/java/com/example/MnM/boundedContext/mbtiTest/controller/MbtiTestController.java
  src/main/resources/templates/about.html
  src/main/resources/templates/header/header.html
  src/main/resources/templates/main.html
Labels: enhancement

#42 Mbti를 활용한 멤버추천
  src/main/java/com/example/MnM/base/config/JasyptConfig.java
  src/main/java/com/example/MnM/base/config/websocket/CustomWebsocketInterceptor.java
  src/main/java/com/example/MnM/base/initData/NotProd.java
  src/main/java/com/example/MnM/boundedContext/chat/infra/InspectSentimentService.java
  src/main/java/com/example/MnM/boundedContext/chat/infra/LocalInspectService.java
  src/main/java/com/example/MnM/boundedContext/chat/service/ChatService.java
  src/main/java/com/example/MnM/boundedContext/chat/service/FacadeChatService.java
  src/main/java/com/example/MnM/boundedContext/likeablePerson/controller/LikeablePersonController.java
  src/main/java/com/example/MnM/boundedContext/likeablePerson/repository/LikeablePersonRepository.java
  src/main/java/com/example/MnM/boundedContext/likeablePerson/service/LikeablePersonService.java
  src/main/java/com/example/MnM/boundedContext/member/controller/MemberController.java
  src/main/java/com/example/MnM/boundedContext/member/entity/Member.java
  src/main/java/com/example/MnM/boundedContext/member/repository/MemberRepository.java
  src/main/java/com/example/MnM/boundedContext/member/service/MemberService.java
  src/main/java/com/example/MnM/boundedContext/recommend/controller/MbtiController.java
  src/main/java/com/example/MnM/boundedContext/recommend/entity/Mbti.java
  src/main/java/com/example/MnM/boundedContext/recommend/repository/MbtiRepository.java
  src/main/java/com/example/MnM/boundedContext/recommend/service/MbtiService.java
  src/main/java/com/example/MnM/boundedContext/recommend/service/MemberMbtiService.java
  src/main/java/com/example/MnM/boundedContext/room/controller/RoomController.java
  src/main/java/com/example/MnM/boundedContext/room/dto/ChatRoomDto.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/static/js/room.js
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/rooms.html
  src/main/resources/templates/member/me.html
  src/main/resources/templates/recommend/member.html
  src/test/java/com/example/MnM/boundedContext/chat/controller/RoomControllerTest.java
  src/test/java/com/example/MnM/boundedContext/chat/infra/InspectSentimentServiceTest.java
  src/test/java/com/example/MnM/boundedContext/chat/service/RoomChatService.java
  src/test/java/com/example/MnM/boundedContext/mbti/service/MbtiServiceTest.java
  src/test/java/com/example/MnM/likeablePerson/service/LikeablePersonServiceTest.java
Labels: enhancement

#63 알림기능
  src/main/java/com/example/MnM/boundedContext/notification/controller/NotificationController.java
  src/main/java/com/example/MnM/boundedContext/notification/entity/Notification.java
  src/main/java/com/example/MnM/boundedContext/notification/repository/NotificationRepository.java
  src/main/java/com/example/MnM/boundedContext/notification/service/NotificationService.java
  src/main/resources/templates/header/header.html
  src/main/resources/templates/notification/list.html
  src/main/resources/templates/recommend/member.html
Labels: enhancement

#74 뒤로가기 시 먼저 나가기 메시지 보내도록 설정
  src/main/java/com/example/MnM/base/config/RedisProdConfig.java
  src/main/java/com/example/MnM/boundedContext/room/service/RoomService.java
  src/main/resources/static/js/room.js
Labels: refactoring

#75 ui 디자인 개선, 채팅방 페이징 처리
  src/main/java/com/example/MnM/boundedContext/room/controller/RoomController.java
  src/main/java/com/example/MnM/boundedContext/room/repository/RoomRepository.java
  src/main/java/com/example/MnM/boundedContext/room/service/RoomService.java
  src/main/resources/templates/board/question_form.html
  src/main/resources/templates/board/question_list.html
  src/main/resources/templates/chat/rooms.html
  src/main/resources/templates/layout/layout.html
  src/main/resources/templates/likeablePerson/fromList.html
  src/main/resources/templates/likeablePerson/like.html
  src/main/resources/templates/likeablePerson/toList.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mbtiTest/mbti.html
  src/main/resources/templates/member/editMyPage.html
  src/main/resources/templates/member/editProfile.html
  src/main/resources/templates/member/join.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/me.html
  src/main/resources/templates/notification/list.html
  src/main/resources/templates/recommend/member.html
Labels: enhancement, refactoring

#77 fix: header.html
  src/main/resources/templates/header/header.html
  src/test/java/com/example/MnM/likeablePerson/service/LikeablePersonServiceTest.java
Labels: fix

#81 fix: controller return
  src/main/java/com/example/MnM/boundedContext/likeablePerson/controller/LikeablePersonController.java
  src/main/java/com/example/MnM/boundedContext/recommend/controller/MbtiController.java
Labels: fix

#79 404, 500 오류 페이지
  src/main/resources/static/css/error.css
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
Labels: enhancement

#88 refactor: MakeAlarmAndCreateRoom
  src/main/java/com/example/MnM/boundedContext/notification/controller/NotificationController.java
  src/main/java/com/example/MnM/boundedContext/notification/entity/Notification.java
  src/main/java/com/example/MnM/boundedContext/notification/service/NotificationService.java
  src/main/resources/templates/notification/list.html
Labels: refactoring

#92 refactor: html 수정
  src/main/resources/templates/header/header.html
  src/main/resources/templates/notification/list.html
  src/main/resources/templates/recommend/member.html
Labels: refactoring

#95 Junsu/93
  src/main/java/com/example/MnM/base/rq/Rq.java
  src/main/java/com/example/MnM/boundedContext/board/controller/QuestionController.java
  src/main/java/com/example/MnM/boundedContext/board/entity/question/Question.java
  src/main/java/com/example/MnM/boundedContext/board/service/QuestionService.java
  src/main/java/com/example/MnM/boundedContext/mbtiboard/controller/MbtiAnswerController.java
  src/main/java/com/example/MnM/boundedContext/mbtiboard/controller/MbtiQuestionController.java
  src/main/java/com/example/MnM/boundedContext/mbtiboard/entity/mbtianswer/MbtiAnswer.java
  src/main/java/com/example/MnM/boundedContext/mbtiboard/entity/mbtianswer/MbtiVote.java
  src/main/java/com/example/MnM/boundedContext/mbtiboard/repository/MbtiQuestionRepository.java
  src/main/java/com/example/MnM/boundedContext/mbtiboard/service/MbtiAnswerService.java
  src/main/java/com/example/MnM/boundedContext/mbtiboard/service/MbtiQuestionService.java
  src/main/java/com/example/MnM/boundedContext/notification/controller/NotificationController.java
  src/main/java/com/example/MnM/boundedContext/notification/entity/Notification.java
  src/main/java/com/example/MnM/boundedContext/notification/repository/NotificationRepository.java
  src/main/java/com/example/MnM/boundedContext/notification/service/NotificationService.java
  src/main/java/com/example/MnM/standard/util/Ut.java
  src/main/resources/templates/board/answer_form.html
  src/main/resources/templates/board/question_detail.html
  src/main/resources/templates/board/question_form.html
  src/main/resources/templates/board/question_list.html
  src/main/resources/templates/header/header.html
  src/main/resources/templates/likeablePerson/fromList.html
  src/main/resources/templates/likeablePerson/like.html
  src/main/resources/templates/likeablePerson/toList.html
  src/main/resources/templates/mbtiboard/mbtianswer_form.html
  src/main/resources/templates/mbtiboard/mbtiquestion_detail.html
  src/main/resources/templates/mbtiboard/mbtiquestion_form.html
  src/main/resources/templates/mbtiboard/mbtiquestion_list.html
  src/main/resources/templates/notification/list.html
Labels: enhancement

#97 Refactor: 네비바 수정
  src/main/resources/templates/header/header.html
Labels: refactoring

#98 채팅 저장 로직 수정
  src/main/java/com/example/MnM/boundedContext/chat/service/ChatService.java
Labels: enhancement, refactoring

#100 header 수정
  src/main/resources/templates/header/header.html
  src/main/resources/templates/mbtiTest/mbti.html
Labels: fix
